spring:
  profiles:
    active: default, development
  application:
    name: tour-editor
    path: /${spring.application.name}
  jackson:
    default-property-inclusion: non_null
application:
  photo-preview:
    width: 400
    height: 200
server:
  port: 8091
  use-forward-headers: true
security:
  basic:
    enabled: false
---
spring:
  profiles: development
  data:
    mongodb:
      uri: mongodb://localhost:27017/panorama-test
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
application:
  baseUrl: http://localhost:8080${spring.application.path}
  nona: /Applications/Hugin/HuginStitchProject.app/Contents/MacOS/nona
  tile-generate-script: /Users/hua/IdeaProjects/pannellum-tour-maker/generate.py
  upload:
    directory: /Users/hua/IdeaProjects/pannellum-tour-maker/upload-dir
    tours: ${application.upload.directory}/tours
    equirectangular: ${application.upload.directory}/equirectangular
security:
  oauth2:
    resource:
      jwt:
        key-value: dev-signature
logging:
  level:
    org.springframework.security: DEBUG
---
spring:
  profiles: production
  data:
    mongodb:
      uri: mongodb://localhost:27017/panorama
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  thymeleaf:
    cache: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
application:
  baseUrl: http://localhost${spring.application.path}
  nona: nona
  tile-generate-script: /home/generate.py
  upload:
    directory: /home/pannellum-tour-maker/upload-dir
    tours: ${application.upload.directory}/tours
    equirectangular: ${application.upload.directory}/equirectangular
logging:
  level:
    org.springframework: ERROR
    com.mongodb: ERROR
security:
  oauth2:
    resource:
      jwt:
        key-value: prod-signature
---
spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb://one-mongo:27017/panorama
  rabbitmq:
    host: one-rabbit
    port: 5672
    username: guest
    password: guest